name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Se le asigna un nombre al 1er paso y la acción es el 'uses'.
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Para realizar búsqueda profunda en el historial de commits.

    # Nombre del Paso 2 y su acción 'run'.
    - name: Docker login
      env:    # Declaración de variables de entorno para usar los secrets.
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: |    # El pipe se utiliza para interpretar las siguiente lineas como independientes.
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del Login"
    
    # Nombre del Paso 3 y su acción 'run'.
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
